import Head from "next/head";
import NavBar from "~/components/NavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <NavBar />
        <main className=" flex min-h-screen flex-col items-center justify-center"></main>
      </>
    </>
  );
}
