import { useSession } from "next-auth/react";
import Head from "next/head";
import Header from "~/components/Header";
import ItemCategories from "~/components/ItemCategories";
import ItemDetails from "~/components/ItemDetails";
import ItemGrid from "~/components/ItemGrid";
import NavBar from "~/components/NavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <NavBar />
        <Header />
        <main className="mb-12 flex min-h-screen  w-screen justify-between px-[10%] pt-12">
          <aside className="min-h-full w-full">
            <ItemDetails />
          </aside>
          <aside className="h-full w-full">
            <ItemCategories />
            <ItemGrid />
          </aside>
        </main>
      </>
    </>
  );
}
